import { StyleSheet } from 'react-native';
import { Colors, Fonts, Layout, Radii, Spacing, Typography } from '@/constants';

export const authFieldStyles = StyleSheet.create({
  shell: { width: '100%' },
  shellIdle: { flexGrow: 1, minHeight: '100%', justifyContent: 'space-between' },
  shellTop: { width: '100%' },
  shellFooter: { width: '100%', gap: Spacing.three, alignItems: 'center' },
  shellFooterCompact: { paddingTop: Spacing.three, marginTop: 0 },
  field: { width: '100%', gap: Spacing.one },
  label: { ...Typography.label, lineHeight: 22, width: '100%' },
  input: {
    height: Layout.inputHeight,
    width: '100%',
    borderWidth: 1,
    borderColor: Colors.steelGray,
    borderRadius: Radii.input,
    paddingHorizontal: Spacing.three,
    fontFamily: Fonts.regular,
    fontSize: 16,
    lineHeight: 16 * 1.6,
    color: Colors.charcoal,
  },
  inputRow: {
    height: Layout.inputHeight,
    width: '100%',
    borderWidth: 1,
    borderColor: Colors.steelGray,
    borderRadius: Radii.input,
    paddingHorizontal: Spacing.three,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  inputFlex: {
    flex: 1,
    fontFamily: Fonts.regular,
    fontSize: 16,
    lineHeight: 16 * 1.6,
    color: Colors.charcoal,
    padding: 0,
  },
  primaryButton: {
    height: Layout.buttonHeight,
    width: '100%',
    borderRadius: Radii.button,
    backgroundColor: Colors.charcoal,
    borderWidth: 1,
    borderColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: Spacing.four,
  },
  primaryButtonGreen: { backgroundColor: Colors.green, borderColor: Colors.green },
  primaryButtonDanger: { backgroundColor: Colors.danger, borderColor: Colors.danger },
  primaryButtonOutline: { backgroundColor: 'transparent', borderWidth: 1.5, borderColor: Colors.charcoal },
  primaryButtonLabel: { ...Typography.buttonBold, lineHeight: 26 },
  primaryButtonLabelDark: { color: Colors.charcoal },
  primaryButtonLabelOutline: { fontFamily: Fonts.semiBold, color: Colors.charcoal },
  disabled: { opacity: 0.6 },
  pressed: { opacity: 0.85 },
  footer: { width: '100%', textAlign: 'center' },
  footerPrefix: { fontFamily: Fonts.regular, fontSize: 16, lineHeight: 16 * 1.6, color: Colors.steelGray },
  footerAction: { fontFamily: Fonts.bold, fontSize: 16, lineHeight: 26, color: Colors.charcoal, textDecorationLine: 'underline' },
  phoneRow: {
    flexDirection: 'row',
    width: '100%',
    alignItems: 'stretch',
  },
  countryCode: {
    height: Layout.inputHeight,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.two,
    paddingLeft: Spacing.three,
    paddingRight: Spacing.one,
    borderWidth: 1,
    borderColor: Colors.steelGray,
    borderTopLeftRadius: Radii.input,
    borderBottomLeftRadius: Radii.input,
  },
  countryCodeText: {
    fontFamily: Fonts.semiBold,
    fontSize: 16,
    lineHeight: 16 * 1.6,
    color: Colors.charcoal,
  },
  phoneInput: {
    flex: 1,
    height: Layout.inputHeight,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderRightWidth: 1,
    borderColor: Colors.steelGray,
    borderTopRightRadius: Radii.input,
    borderBottomRightRadius: Radii.input,
    paddingHorizontal: Spacing.three,
    fontFamily: Fonts.regular,
    fontSize: 16,
    lineHeight: 16 * 1.6,
    color: Colors.charcoal,
  },
});
